/**
 * An array of Cypher queries to create all Person nodes.
 * Each item in the array is a single CREATE query.
 */
export const peopleQueries = [
    'CREATE (:Person { name: "محمد ﷺ", slug: "prophet-muhammad", nameTransliterated: "Muhammad (Peace be upon him)" });',
    'CREATE (:Person { name: "أبو بكر الصديق", slug: "abu-bakr-as-siddiq", nameTransliterated: "Abu Bakr al-Siddiq" });',
    'CREATE (:Person { name: "عمر بن الخطاب", slug: "umar-ibn-al-khattab", nameTransliterated: "Umar ibn al-Khattab" });',
    'CREATE (:Person { name: "عثمان بن عفان", slug: "uthman-ibn-affan", nameTransliterated: "Uthman ibn Affan" });',
    'CREATE (:Person { name: "علي بن أبي طالب", slug: "ali-ibn-abi-talib", nameTransliterated: "Ali ibn Abi Talib" });',
    'CREATE (:Person { name: "الزبير بن العوام", slug: "az-zubayr-ibn-al-awwam", nameTransliterated: "Az-Zubayr ibn al-Awwam" });',
    'CREATE (:Person { name: "طلحة بن عبيد الله", slug: "talhah-ibn-ubaydullah", nameTransliterated: "Talhah ibn Ubaydullah" });',
    'CREATE (:Person { name: "عبد الرحمن بن عوف", slug: "abdur-rahman-ibn-awf", nameTransliterated: "Abdur Rahman ibn Awf" });',
    'CREATE (:Person { name: "سعد بن أبي وقاص", slug: "saad-ibn-abi-waqqas", nameTransliterated: "Saad ibn Abi Waqqas" });',
    'CREATE (:Person { name: "سعيد بن زيد", slug: "saeed-ibn-zaid", nameTransliterated: "Saeed ibn Zaid" });',
    'CREATE (:Person { name: "أبو عبيدة بن الجراح", slug: "abu-ubaydah-ibn-al-jarrah", nameTransliterated: "Abu Ubaydah ibn al-Jarrah" });',
    'CREATE (:Person { name: "خديجة بنت خويلد", slug: "khadijah-bint-khuwaylid", nameTransliterated: "Khadijah bint Khuwaylid" });',
    'CREATE (:Person { name: "عائشة بنت أبي بكر", slug: "aisha-bint-abi-bakr", nameTransliterated: "Aisha bint Abi Bakr" });',
    'CREATE (:Person { name: "حفصة بنت عمر", slug: "hafsa-bint-umar", nameTransliterated: "Hafsa bint Umar" });',
    'CREATE (:Person { name: "زينب بنت خزيمة", slug: "zaynab-bint-khuzaymah", nameTransliterated: "Zaynab bint Khuzaymah" });',
    'CREATE (:Person { name: "أم سلمة", slug: "umm-salamah", nameTransliterated: "Umm Salamah" });',
    'CREATE (:Person { name: "زينب بنت جحش", slug: "zaynab-bint-jahsh", nameTransliterated: "Zaynab bint Jahsh" });',
    'CREATE (:Person { name: "جويرية بنت الحارث", slug: "juwayriyah-bint-al-harith", nameTransliterated: "Juwayriyah bint al-Harith" });',
    'CREATE (:Person { name: "أم حبيبة", slug: "umm-habibah", nameTransliterated: "Umm Habibah" });',
    'CREATE (:Person { name: "صفية بنت حيي", slug: "safiyyah-bint-huyayy", nameTransliterated: "Safiyyah bint Huyayy" });',
    'CREATE (:Person { name: "ميمونة بنت الحارث", slug: "maymunah-bint-al-harith", nameTransliterated: "Maymunah bint al-Harith" });',
    'CREATE (:Person { name: "سودة بنت زمعة", slug: "sawdah-bint-zamah", nameTransliterated: "Sawdah bint Zam\'ah" });',
    'CREATE (:Person { name: "فاطمة الزهراء", slug: "fatimah-al-zahra", nameTransliterated: "Fatimah al-Zahra" });',
    'CREATE (:Person { name: "زينب بنت محمد", slug: "zaynab-bint-muhammad", nameTransliterated: "Zaynab bint Muhammad" });',
    'CREATE (:Person { name: "رقية بنت محمد", slug: "ruqayyah-bint-muhammad", nameTransliterated: "Ruqayyah bint Muhammad" });',
    'CREATE (:Person { name: "أم كلثوم بنت محمد", slug: "umm-kulthum-bint-muhammad", nameTransliterated: "Umm Kulthum bint Muhammad" });',
    'CREATE (:Person { name: "القاسم بن محمد", slug: "al-qasim-ibn-muhammad", nameTransliterated: "Al-Qasim ibn Muhammad" });',
    'CREATE (:Person { name: "عبد الله بن محمد", slug: "abdullah-ibn-muhammad", nameTransliterated: "Abdullah ibn Muhammad" });',
    'CREATE (:Person { name: "إبراهيم بن محمد", slug: "ibrahim-ibn-muhammad", nameTransliterated: "Ibrahim ibn Muhammad" });',
    'CREATE (:Person { name: "حمزة بن عبد المطلب", slug: "hamzah-ibn-abd-al-muttalib", nameTransliterated: "Hamzah ibn Abd al-Muttalib" });',
    'CREATE (:Person { name: "أبو طالب", slug: "abu-talib", nameTransliterated: "Abu Talib" });',
    'CREATE (:Person { name: "العباس بن عبد المطلب", slug: "al-abbas-ibn-abd-al-muttalib", nameTransliterated: "Al-Abbas ibn Abd al-Muttalib" });',
    'CREATE (:Person { name: "الحسن بن علي", slug: "al-hasan-ibn-ali", nameTransliterated: "Al-Hasan ibn Ali" });',
    'CREATE (:Person { name: "الحسين بن علي", slug: "al-husayn-ibn-ali", nameTransliterated: "Al-Husayn ibn Ali" });',
    'CREATE (:Person { name: "عبد الله بن جعفر", slug: "abdullah-ibn-jaafar", nameTransliterated: "Abdullah ibn Jafar" });',
    'CREATE (:Person { name: "أم كلثوم بنت علي", slug: "umm-kulthum-bint-ali", nameTransliterated: "Umm Kulthum bint Ali" });',
    'CREATE (:Person { name: "زينب بنت علي", slug: "zaynab-bint-ali", nameTransliterated: "Zaynab bint Ali" });',
];

/**
 * An array of Cypher queries to create all relationships between Person nodes.
 * Each item in the array is a single MATCH...CREATE query.
 */
export const peopleRelationsQueries = [
    'MATCH (from:Person {slug: "saad-ibn-abi-waqqas"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:MATERNAL_UNCLE]->(to);',
    'MATCH (from:Person {slug: "prophet-muhammad"}), (to:Person {slug: "saad-ibn-abi-waqqas"}) CREATE (from)-[:MATERNAL_NEPHEW]->(to);',
    'MATCH (from:Person {slug: "abu-bakr-as-siddiq"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:FATHER_IN_LAW]->(to);',
    'MATCH (from:Person {slug: "umar-ibn-al-khattab"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:FATHER_IN_LAW]->(to);',
    'MATCH (from:Person {slug: "uthman-ibn-affan"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:SON_IN_LAW]->(to);',
    'MATCH (from:Person {slug: "ali-ibn-abi-talib"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:SON_IN_LAW]->(to);',
    'MATCH (from:Person {slug: "az-zubayr-ibn-al-awwam"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_COUSIN]->(to);',
    'MATCH (from:Person {slug: "khadijah-bint-khuwaylid"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "aisha-bint-abi-bakr"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "hafsa-bint-umar"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "zaynab-bint-khuzaymah"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "umm-salamah"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "zaynab-bint-jahsh"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "juwayriyah-bint-al-harith"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "umm-habibah"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "safiyyah-bint-huyayy"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "maymunah-bint-al-harith"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "sawdah-bint-zamah"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "fatimah-al-zahra"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "zaynab-bint-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "ruqayyah-bint-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "umm-kulthum-bint-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "al-qasim-ibn-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:SON]->(to);',
    'MATCH (from:Person {slug: "abdullah-ibn-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:SON]->(to);',
    'MATCH (from:Person {slug: "ibrahim-ibn-muhammad"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:SON]->(to);',
    'MATCH (from:Person {slug: "hamzah-ibn-abd-al-muttalib"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_UNCLE]->(to);',
    'MATCH (from:Person {slug: "abu-talib"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_UNCLE]->(to);',
    'MATCH (from:Person {slug: "al-abbas-ibn-abd-al-muttalib"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_UNCLE]->(to);',
    'MATCH (from:Person {slug: "al-hasan-ibn-ali"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:GRANDSON]->(to);',
    'MATCH (from:Person {slug: "al-husayn-ibn-ali"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:GRANDSON]->(to);',
    'MATCH (from:Person {slug: "ali-ibn-abi-talib"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_COUSIN]->(to);',
    'MATCH (from:Person {slug: "abdullah-ibn-jaafar"}), (to:Person {slug: "prophet-muhammad"}) CREATE (from)-[:PATERNAL_COUSIN]->(to);',
    'MATCH (from:Person {slug: "fatimah-al-zahra"}), (to:Person {slug: "ali-ibn-abi-talib"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "ali-ibn-abi-talib"}), (to:Person {slug: "fatimah-al-zahra"}) CREATE (from)-[:HUSBAND]->(to);',
    'MATCH (from:Person {slug: "al-hasan-ibn-ali"}), (to:Person {slug: "fatimah-al-zahra"}) CREATE (from)-[:MOTHER]->(to);',
    'MATCH (from:Person {slug: "al-hasan-ibn-ali"}), (to:Person {slug: "ali-ibn-abi-talib"}) CREATE (from)-[:FATHER]->(to);',
    'MATCH (from:Person {slug: "al-husayn-ibn-ali"}), (to:Person {slug: "fatimah-al-zahra"}) CREATE (from)-[:MOTHER]->(to);',
    'MATCH (from:Person {slug: "al-husayn-ibn-ali"}), (to:Person {slug: "ali-ibn-abi-talib"}) CREATE (from)-[:FATHER]->(to);',
    'MATCH (from:Person {slug: "umm-kulthum-bint-ali"}), (to:Person {slug: "fatimah-al-zahra"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "umm-kulthum-bint-ali"}), (to:Person {slug: "ali-ibn-abi-talib"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "zaynab-bint-ali"}), (to:Person {slug: "fatimah-al-zahra"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "zaynab-bint-ali"}), (to:Person {slug: "ali-ibn-abi-talib"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "ruqayyah-bint-muhammad"}), (to:Person {slug: "uthman-ibn-affan"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "uthman-ibn-affan"}), (to:Person {slug: "ruqayyah-bint-muhammad"}) CREATE (from)-[:HUSBAND]->(to);',
    'MATCH (from:Person {slug: "umm-kulthum-bint-muhammad"}), (to:Person {slug: "uthman-ibn-affan"}) CREATE (from)-[:WIFE]->(to);',
    'MATCH (from:Person {slug: "uthman-ibn-affan"}), (to:Person {slug: "umm-kulthum-bint-muhammad"}) CREATE (from)-[:HUSBAND]->(to);',
    'MATCH (from:Person {slug: "aisha-bint-abi-bakr"}), (to:Person {slug: "abu-bakr-as-siddiq"}) CREATE (from)-[:DAUGHTER]->(to);',
    'MATCH (from:Person {slug: "hafsa-bint-umar"}), (to:Person {slug: "umar-ibn-al-khattab"}) CREATE (from)-[:DAUGHTER]->(to);',
];
