// Sample article data for seeding
export const articleData = [
  {
    title: "غزوة بدر",
    titleEn: "The Battle of Badr",
    summary: "أول معركة كبرى في الإسلام",
    summaryEn: "The first major battle in Islam",
    content: `وقعت معركة بدر في السنة الثانية للهجرة بين المسلمين وقريش. كانت نقطة تحول في تاريخ الإسلام حيث انتصر المسلمون رغم قلة عددهم. أظهرت المعركة قوة الإيمان والتخطيط العسكري لدى المسلمين.\n\nشارك في المعركة حوالي 313 من المسلمين مقابل أكثر من 900 من قريش. انتهت المعركة بانتصار المسلمين وأسر عدد كبير من قريش.\n\nتعد معركة بدر من أهم الأحداث التي عززت مكانة المسلمين في المدينة وأرست قواعد الدولة الإسلامية الناشئة.`,
    contentEn: `The Battle of Badr took place in the second year after the Hijra between the Muslims and Quraysh. It was a turning point in Islamic history, as the Muslims achieved victory despite being outnumbered. The battle demonstrated the strength of faith and military strategy among the Muslims.\n\nAbout 313 Muslims participated against more than 900 Quraysh. The battle ended with a Muslim victory and the capture of many Quraysh.\n\nThe Battle of Badr is one of the most important events that strengthened the position of Muslims in Medina and laid the foundations of the emerging Islamic state.`,
    slug: "battle-of-badr",
    img: null,
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    categories: ["battles"]
  },
  {
    title: "الهجرة النبوية",
    titleEn: "The Prophetic Migration",
    summary: "هجرة النبي محمد من مكة إلى المدينة",
    summaryEn: "The migration of Prophet Muhammad from Mecca to Medina",
    content: `الهجرة النبوية هي الحدث التاريخي الذي انتقل فيه النبي محمد صلى الله عليه وسلم وأصحابه من مكة إلى المدينة المنورة في السنة الثالثة عشرة للبعثة. جاءت الهجرة بعد سنوات من الاضطهاد والمعاناة التي تعرض لها المسلمون في مكة، فكانت نقطة تحول في تاريخ الإسلام وبداية تأسيس الدولة الإسلامية في المدينة.\n\nاستقبل أهل المدينة (الأنصار) النبي وأصحابه بحفاوة، وأسس النبي مجتمعًا جديدًا قائمًا على الأخوة والعدل.\n\nالهجرة لم تكن مجرد انتقال جغرافي، بل كانت رمزًا للتضحية والثبات على العقيدة، وأصبحت بداية التقويم الهجري.`,
    contentEn: `The Prophetic Migration (Hijra) is the historic event in which Prophet Muhammad (peace be upon him) and his companions migrated from Mecca to Medina in the thirteenth year of the Prophethood. The migration came after years of persecution and hardship faced by the Muslims in Mecca, marking a turning point in Islamic history and the beginning of the Islamic state in Medina.\n\nThe people of Medina (the Ansar) warmly welcomed the Prophet and his companions, and the Prophet established a new community based on brotherhood and justice.\n\nThe migration was not just a physical journey, but a symbol of sacrifice and steadfastness in faith, and it became the starting point of the Islamic calendar (Hijri calendar).`,
    slug: "prophetic-migration",
    img: null,
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    categories: ["hijra"]
  },
  {
    title: "الكعبة المشرفة",
    titleEn: "The Holy Kaaba",
    summary: "تاريخ وأهمية الكعبة في الإسلام",
    summaryEn: "The history and significance of the Kaaba in Islam",
    content: `الكعبة هي قبلة المسلمين وأقدس موقع في الإسلام. تقع في وسط المسجد الحرام بمكة المكرمة، ويعود تاريخ بنائها إلى النبي إبراهيم وابنه إسماعيل عليهما السلام.\n\nتعتبر الكعبة مركزًا للعبادة منذ آلاف السنين، ويؤدي المسلمون حولها مناسك الحج والعمرة سنويًا.\n\nتغطي الكعبة كسوة سوداء مطرزة بالذهب، وتعد رمزًا للوحدة الإسلامية.`,
    contentEn: `The Kaaba is the qibla for Muslims and the holiest site in Islam. It is located at the center of Masjid al-Haram in Mecca, and its construction dates back to Prophet Abraham and his son Ishmael (peace be upon them).\n\nThe Kaaba has been a center of worship for thousands of years, and Muslims perform the Hajj and Umrah rituals around it every year.\n\nThe Kaaba is covered with a black cloth embroidered with gold and is a symbol of Islamic unity.`,
    slug: "kaaba",
    img: null,
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    categories: ["history"]
  },
  {
    title: "اللغة العربية",
    titleEn: "The Arabic Language",
    summary: "مكانة اللغة العربية وتاريخها",
    summaryEn: "The status and history of the Arabic language",
    content: `اللغة العربية هي لغة القرآن الكريم وإحدى أقدم اللغات السامية. تتميز بغناها اللغوي وبلاغتها، وتعد من أكثر اللغات انتشارًا في العالم الإسلامي.\n\nتطورت اللغة العربية عبر العصور وأثرت في العديد من اللغات الأخرى.\n\nتحتل مكانة خاصة في قلوب المسلمين كونها لغة العبادة والقرآن.`,
    contentEn: `Arabic is the language of the Holy Quran and one of the oldest Semitic languages. It is known for its linguistic richness and eloquence, and is one of the most widely spoken languages in the Islamic world.\n\nArabic has evolved over the centuries and has influenced many other languages.\n\nIt holds a special place in the hearts of Muslims as the language of worship and the Quran.`,
    slug: "arabic-language",
    isPublished: true,
    special: true,
    img: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    categories: ["arabic"]
  },
  {
    // add one about the arabic letters
    title: "الحروف العربية",
    titleEn: "The Arabic Letters",
    summary: "إتقان الحروف العربية هو الخطوة الأولى لفهم اللغة وقراءة القرآن الكريم. ابدأ رحلتك مع الأبجدية العربية وتعرف على أشكال الحروف وأصواتها من خلال أمثلة تفاعلية ومبسطة.",
    summaryEn: "Mastering the Arabic letters is the first step to understanding the language and reading the Holy Quran. Start your journey with the Arabic alphabet and discover the shapes and sounds of the letters through interactive and simple examples.",
    content: "اللغة العربية لغة عريقة ضاربة في أعماق التاريخ، حملت عبر حروفها الثمانية والعشرين تراث أمة كاملة وعلومها وآدابها. صمدت العربية أمام تحديات الزمن، وانتشرت في بقاع الأرض، وبقيت لغة القرآن الكريم والعلوم والفكر. حروفها ليست مجرد رموز، بل مفاتيح لفهم حضارة عظيمة، وستظل العربية حية نابضة في قلوب الملايين لأجيال قادمة.",
    contentEn: "The Arabic language is a unique and rich language that dates back to the depths of history. It carried through its 28 letters the heritage of a complete nation and its sciences and arts. Arabic stood against the challenges of time and spread across the world. It remained the language of the Hol y Quran, science, and thought. Its letters are not mere symbols, but keys to understanding a great civilization, and will remain Arabic alive and vibrant in the hearts of millions for generations to come.",
    slug: "arabic-letters",
    isPublished: true,
    special: true,
    img: null,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    categories: ["arabic"]
  }
]; 