// Article seed data for use in prisma/seed.ts

export const articles = [
  {
    title: 'Arabic Letters',
    titleAr: 'الحروف العربية',
    description: 'Learn the Arabic alphabet and letter forms',
    descriptionAr: 'تعلم الأبجدية العربية وأشكال الحروف',
    content: 'Content about Arabic letters...',
    contentAr: 'محتوى عن الحروف العربية...',
    slug: 'arabic-letters',
    icon: 'font',
    color: 'indigo',
    order: 1,
    isPublished: true,
    publishedAt: new Date(),
    categorySlug: 'arabic-language',
  },
  {
    title: 'Prophet Muhammad ﷺ',
    titleAr: 'النبي محمد ﷺ',
    description: 'Learn about the life and teachings of Prophet Muhammad',
    descriptionAr: 'تعلم عن حياة وتعاليم النبي محمد',
    content: 'Content about Prophet Muhammad...',
    contentAr: 'محتوى عن النبي محمد...',
    slug: 'prophet-muhammad',
    icon: 'user',
    color: 'green',
    order: 1,
    isPublished: true,
    publishedAt: new Date(),
    categorySlug: 'islamic-history',
  },
  {
    title: 'The Companions',
    titleAr: 'الصحابة',
    description: 'Learn about the companions of Prophet Muhammad',
    descriptionAr: 'تعلم عن صحابة النبي محمد',
    content: 'Content about the companions...',
    contentAr: 'محتوى عن الصحابة...',
    slug: 'companions',
    icon: 'users',
    color: 'purple',
    order: 2,
    isPublished: true,
    publishedAt: new Date(),
    categorySlug: 'islamic-history',
  },
]; 