export const battles = [
  {
    name: 'غزوة بدر',
    slug: 'badr',
    location: 'بدر',
    hijri_year: 2,
    nameEn: 'Battle of Badr',
    locationEn: 'Badr',
  },
  {
    name: 'غزوة أحد',
    slug: 'uhud',
    location: 'أحد',
    hijri_year: 3,
    nameEn: 'Battle of Uhud',
    locationEn: 'Uhud',
  },
  {
    name: 'غزوة الخندق',
    slug: 'khandaq',
    location: 'المدينة المنورة',
    hijri_year: 5,
    nameEn: 'Battle of the Trench',
    locationEn: 'Medina',
  },
  {
    name: 'غزوة بني قريظة',
    slug: 'banu-qurayzah',
    location: 'المدينة المنورة',
    hijri_year: 5,
    nameEn: 'Siege of Banu Qurayzah',
    locationEn: 'Medina',
  },
  {
    name: 'صلح الحديبية',
    slug: 'hudaybiyyah',
    location: 'الحديبية',
    hijri_year: 6,
    nameEn: 'Treaty of Hudaybiyyah',
    locationEn: 'Hudaybiyyah',
  },
  {
    name: 'غزوة خيبر',
    slug: 'khaybar',
    location: 'خيبر',
    hijri_year: 7,
    nameEn: 'Battle of Khaybar',
    locationEn: 'Khaybar',
  },
  {
    name: 'غزوة مؤتة',
    slug: 'mutah',
    location: 'مؤتة',
    hijri_year: 8,
    nameEn: 'Battle of Mu\'tah',
    locationEn: 'Mu\'tah',
  },
  {
    name: 'فتح مكة',
    slug: 'fath-makkah',
    location: 'مكة المكرمة',
    hijri_year: 8,
    nameEn: 'Conquest of Mecca',
    locationEn: 'Mecca',
  },
  {
    name: 'غزوة حنين',
    slug: 'hunayn',
    location: 'حنين',
    hijri_year: 8,
    nameEn: 'Battle of Hunayn',
    locationEn: 'Hunayn',
  },
  {
    name: 'غزوة الطائف',
    slug: 'taif',
    location: 'الطائف',
    hijri_year: 8,
    nameEn: 'Siege of Taif',
    locationEn: 'Taif',
  },
  {
    name: 'غزوة تبوك',
    slug: 'tabuk',
    location: 'تبوك',
    hijri_year: 9,
    nameEn: 'Expedition of Tabuk',
    locationEn: 'Tabuk',
  },
  {
    name: 'معركة ذات السلاسل',
    slug: 'zat-as-salasil',
    location: 'العراق',
    hijri_year: 12,
    nameEn: 'Battle of Chains',
    locationEn: 'Iraq',
  },
  {
    name: 'معركة أجنادين',
    slug: 'ajnadayn',
    location: 'فلسطين',
    hijri_year: 13,
    nameEn: 'Battle of Ajnadayn',
    locationEn: 'Palestine',
  },
  {
    name: 'معركة فحل',
    slug: 'fihl',
    location: 'الأردن',
    hijri_year: 13,
    nameEn: 'Battle of Fihl',
    locationEn: 'Jordan',
  },
  {
    name: 'معركة اليرموك',
    slug: 'yarmuk',
    location: 'الأردن',
    hijri_year: 15,
    nameEn: 'Battle of Yarmuk',
    locationEn: 'Jordan',
  },
  {
    name: 'فتح دمشق',
    slug: 'fath-damascus',
    location: 'دمشق',
    hijri_year: 14,
    nameEn: 'Conquest of Damascus',
    locationEn: 'Damascus',
  },
  {
    name: 'فتح بيت المقدس',
    slug: 'fath-jerusalem',
    location: 'القدس',
    hijri_year: 16,
    nameEn: 'Conquest of Jerusalem',
    locationEn: 'Jerusalem',
  },
  {
    name: 'معركة القادسية',
    slug: 'qadisiyyah',
    location: 'العراق',
    hijri_year: 15,
    nameEn: 'Battle of al-Qadisiyyah',
    locationEn: 'Iraq',
  },
  {
    name: 'فتح المدائن',
    slug: 'fath-ctesiphon',
    location: 'العراق',
    hijri_year: 16,
    nameEn: 'Conquest of Ctesiphon',
    locationEn: 'Iraq',
  },
  {
    name: 'معركة نهاوند',
    slug: 'nahavand',
    location: 'إيران',
    hijri_year: 21,
    nameEn: 'Battle of Nahavand',
    locationEn: 'Iran',
  },
  {
    name: 'فتح الإسكندرية',
    slug: 'fath-alexandria',
    location: 'مصر',
    hijri_year: 20,
    nameEn: 'Conquest of Alexandria',
    locationEn: 'Egypt',
  },
  {
    name: 'معركة ذات الصواري',
    slug: 'zat-as-sawari',
    location: 'البحر المتوسط',
    hijri_year: 34,
    nameEn: 'Battle of the Masts',
    locationEn: 'Mediterranean Sea',
  },
  {
    name: 'فتح قبرص',
    slug: 'fath-cyprus',
    location: 'قبرص',
    hijri_year: 28,
    nameEn: 'Conquest of Cyprus',
    locationEn: 'Cyprus',
  },
  {
    name: 'معركة صفين',
    slug: 'siffin',
    location: 'سوريا',
    hijri_year: 37,
    nameEn: 'Battle of Siffin',
    locationEn: 'Syria',
  },
  {
    name: 'معركة الجمل',
    slug: 'jamal',
    location: 'البصرة',
    hijri_year: 36,
    nameEn: 'Battle of the Camel',
    locationEn: 'Basra',
  },
  {
    name: 'معركة النهروان',
    slug: 'nahrawan',
    location: 'العراق',
    hijri_year: 38,
    nameEn: 'Battle of Nahrawan',
    locationEn: 'Iraq',
  },
  {
    name: 'معركة كربلاء',
    slug: 'karbala',
    location: 'كربلاء',
    hijri_year: 61,
    nameEn: 'Battle of Karbala',
    locationEn: 'Karbala',
  },
  {
    name: 'فتح الأندلس',
    slug: 'fath-andalus',
    location: 'الأندلس',
    hijri_year: 92,
    nameEn: 'Conquest of Al-Andalus',
    locationEn: 'Iberian Peninsula',
  },
  {
    name: 'معركة بلاط الشهداء',
    slug: 'balat-ash-shuhada',
    location: 'فرنسا',
    hijri_year: 114,
    nameEn: 'Battle of Tours',
    locationEn: 'France',
  },
]; 