// Sample category data for seeding
export const categoryData = [
  {
    name: "غزوات و معارك",
    nameTransliterated: "Battles",
    description: "معارك تاريخية كبرى",
    descriptionTransliterated: "Major historical battles",
    img: null,
    slug: "battles",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "الهجرة",
    nameTransliterated: "Migration",
    description: "أحداث الهجرة النبوية",
    descriptionTransliterated: "Events of the Prophetic Migration",
    img: null,
    slug: "hijra",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "العربية",
    nameTransliterated: "Arabic",
    description: "كل ما يتعلق باللغة العربية",
    descriptionTransliterated: "All about the Arabic language",
    img: null,
    slug: "arabic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "تاريخ",
    nameTransliterated: "History",
    description: "مواضيع تاريخية",
    descriptionTransliterated: "Historical topics",
    img: null,
    slug: "history",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "النحو",
    nameTransliterated: "Arabic Grammar",
    description: "قواعد النحو والصرف في اللغة العربية",
    descriptionTransliterated: "Grammar and morphology rules of the Arabic language",
    img: null,
    slug: "arabic-grammar",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "الشعر العربي",
    nameTransliterated: "Arabic Poems",
    description: "قصائد وأشعار عربية مختارة",
    descriptionTransliterated: "Selected Arabic poems and poetry",
    img: null,
    slug: "arabic-poems",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "العلوم",
    nameTransliterated: "Science",
    description: "علوم واكتشافات",
    descriptionTransliterated: "Sciences and discoveries",
    img: null,
    slug: "science",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

]; 