// Sample category data for seeding
export const categoryData = [
  {
    name: "غزوات و معارك",
    nameEn: "Battles",
    description: "معارك تاريخية كبرى",
    descriptionEn: "Major historical battles",
    img: null,
    slug: "battles",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "الهجرة",
    nameEn: "Migration",
    description: "أحداث الهجرة النبوية",
    descriptionEn: "Events of the Prophetic Migration",
    img: null,
    slug: "hijra",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "العربية",
    nameEn: "Arabic",
    description: "كل ما يتعلق باللغة العربية",
    descriptionEn: "All about the Arabic language",
    img: null,
    slug: "arabic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "تاريخ",
    nameEn: "History",
    description: "مواضيع تاريخية",
    descriptionEn: "Historical topics",
    img: null,
    slug: "history",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "النحو",
    nameEn: "Arabic Grammar",
    description: "قواعد النحو والصرف في اللغة العربية",
    descriptionEn: "Grammar and morphology rules of the Arabic language",
    img: null,
    slug: "arabic-grammar",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "الشعر العربي",
    nameEn: "Arabic Poems",
    description: "قصائد وأشعار عربية مختارة",
    descriptionEn: "Selected Arabic poems and poetry",
    img: null,
    slug: "arabic-poems",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]; 