export const people = [
  {
    name: 'عبد الله بن عبد المطلب',
    fullName: 'عبد الله بن عبد المطلب بن هاشم بن عبد مناف بن قصي بن كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'abdullah-ibn-abd-al-muttalib',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عبد المطلب بن هاشم',
    fullName: 'عبد المطلب بن هاشم بن عبد مناف بن قصي بن كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'abd-al-muttalib-ibn-hashim',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'هاشم بن عبد مناف',
    fullName: 'هاشم بن عبد مناف بن قصي بن كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'hashim-ibn-abd-manaf',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عبد مناف بن قصي',
    fullName: 'عبد مناف بن قصي بن كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'abd-manaf-ibn-qusay',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'قصي بن كلاب',
    fullName: 'قصي بن كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'qusay-ibn-kilab',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'كلاب بن مرة',
    fullName: 'كلاب بن مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'kilab-ibn-murra',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'مرة بن كعب',
    fullName: 'مرة بن كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'murra-ibn-kaab',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'كعب بن لؤي',
    fullName: 'كعب بن لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'kaab-ibn-luay',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'لؤي بن غالب',
    fullName: 'لؤي بن غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'luay-ibn-ghalib',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'غالب بن فهر',
    fullName: 'غالب بن فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'ghalib-ibn-fahar',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'فهر بن مالك',
    fullName: 'فهر بن مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'fahar-ibn-malik',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'مالك بن النضر',
    fullName: 'مالك بن النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'malik-ibn-an-nadr',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'النضر بن كنانة',
    fullName: 'النضر بن كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'an-nadr-ibn-kinanah',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'كنانة بن خزيمة',
    fullName: 'كنانة بن خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'kinanah-ibn-khuzayma',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'خزيمة بن مدركة',
    fullName: 'خزيمة بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'khuzayma-ibn-mudrika',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'مدركة بن إلياس',
    fullName: 'مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'mudrika-ibn-ilias',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'إلياس بن مضر',
    fullName: 'إلياس بن مضر بن نزار بن معد بن عدنان.',
    slug: 'ilias-ibn-mudar',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'مضر بن نزار',
    fullName: 'مضر بن نزار بن معد بن عدنان.',
    slug: 'mudar-ibn-nizar',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'نزار بن معد',
    fullName: 'نزار بن معد بن عدنان.',
    slug: 'nizar-ibn-maad',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'معد بن عدنان',
    fullName: 'معد بن عدنان.',
    slug: 'maad-ibn-adnan',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عدنان',
    fullName: 'عدنان',
    slug: 'adnan',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عثمان بن عامر',
    fullName: 'عثمان بن عامر بن عمرو بن كعب بن سعد بن تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'uthman-ibn-amir',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عامر بن عمرو',
    fullName: 'عامر بن عمرو بن كعب بن سعد بن تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'amir-ibn-amr',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عمرو بن كعب',
    fullName: 'عمرو بن كعب بن سعد بن تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'amr-ibn-kaab',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'كعب بن سعد',
    fullName: 'كعب بن سعد بن تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'kaab-ibn-saad',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'سعد بن تيم',
    fullName: 'سعد بن تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'saad-ibn-taym',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'تيم بن مرة',
    fullName: 'تيم بن مرة بن كعب بن لؤي القرشي التيمي',
    slug: 'taym-ibn-murrah',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عمر بن الخطاب',
    fullName: 'عمر بن الخطاب بن نفيل بن عبد العزى بن رياح بن قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'umar-ibn-al-khattab',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'الخطاب بن نفيل',
    fullName: 'الخطاب بن نفيل بن عبد العزى بن رياح بن قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'al-khattab-ibn-nufayl',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'نفيل بن عبد العزى',
    fullName: 'نفيل بن عبد العزى بن رياح بن قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'nufayl-ibn-abd-al-uzza',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عبد العزى بن رياح',
    fullName: 'عبد العزى بن رياح بن قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'abd-al-uzza-ibn-riyah',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'رياح بن قرط',
    fullName: 'رياح بن قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'riyah-ibn-qurt',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'قرط بن رزاح',
    fullName: 'قرط بن رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'qurt-ibn-razah',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'رزاح بن عدي',
    fullName: 'رزاح بن عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'razah-ibn-adi',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عدي بن كعب',
    fullName: 'عدي بن كعب بن لؤي القرشي العدوي',
    slug: 'adi-ibn-kaab',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عفان بن أبي العاص',
    fullName: 'عفان بن أبي العاص بن أمية بن عبد شمس القرشي الأموي',
    slug: 'affan-ibn-abi-al-as',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'أبي العاص بن أمية',
    fullName: 'أبي العاص بن أمية بن عبد شمس القرشي الأموي',
    slug: 'abi-al-as-ibn-umayya',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'أمية بن عبد شمس',
    fullName: 'أمية بن عبد شمس القرشي الأموي',
    slug: 'umayya-ibn-abd-shams',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
  {
    name: 'عبد شمس بن عبد مناف',
    fullName: 'عبد شمس بن عبد مناف القرشي',
    slug: 'abd-shams-ibn-abd-manaf',
    appearance: '',
    virtues: '',
    picture: null,
    titles: [],
  },
];