/**
 * Batch 1 of companion names extracted from "سير أعلام النبلاء" (al-Dhahabi),
 * following the book's entries in order (islamweb bookid=60), starting after
 * the ten already seeded in personSeedData.ts. Name/slug only for this pass —
 * appearance/virtues/fullName are left for a later enrichment batch.
 */
export const people = [
  {
    name: 'مصعب بن عمير',
    fullName: null,
    slug: 'musab-ibn-umayr',
    nameTransliterated: 'Musab ibn Umayr',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'أبو سلمة',
    fullName: null,
    slug: 'abu-salamah',
    nameTransliterated: 'Abu Salamah',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'عثمان بن مظعون',
    fullName: null,
    slug: 'uthman-ibn-mazun',
    nameTransliterated: 'Uthman ibn Mazun',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'قدامة بن مظعون',
    fullName: null,
    slug: 'qudamah-ibn-mazun',
    nameTransliterated: 'Qudamah ibn Mazun',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'عبد الله بن مظعون الجمحي',
    fullName: null,
    slug: 'abdullah-ibn-mazun-al-jumahi',
    nameTransliterated: 'Abdullah ibn Mazun al-Jumahi',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'السائب بن عثمان',
    fullName: null,
    slug: 'as-saib-ibn-uthman',
    nameTransliterated: 'As-Saib ibn Uthman',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'أبو حذيفة',
    fullName: null,
    slug: 'abu-hudhayfah',
    nameTransliterated: 'Abu Hudhayfah',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'سالم مولى أبي حذيفة',
    fullName: null,
    slug: 'salim-mawla-abi-hudhayfah',
    nameTransliterated: 'Salim, mawla of Abi Hudhayfah',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'عاقل بن البكير',
    fullName: null,
    slug: 'aqil-ibn-al-bukayr',
    nameTransliterated: 'Aqil ibn al-Bukayr',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
  {
    name: 'خالد بن البكير',
    fullName: null,
    slug: 'khalid-ibn-al-bukayr',
    nameTransliterated: 'Khalid ibn al-Bukayr',
    appearance: null,
    virtues: null,
    picture: null,
    titles: ['companion'],
  },
];
